accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('articles/', views.index, name='index'),
    path('<int:article_pk>/articles/', views.pur_index, name='pur_index'),
    path('articles/index_search/', views.index_search, name='index_search'),
    path('articles/create/', views.create, name='create'),
    path('articles/<int:article_pk>/', views.detail, name='detail'),
    path("articles/<int:article_pk>/update", views.update, name="update"),
    path('articles/<int:article_pk>/delete/', views.delete, name='delete'),
    path('articles/<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('', include('movies.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.first, name='first'),
    path('movies/', views.movie_list, name='movie_list'),
    # path('movies/movie_filter/<int:genre_pk>/', views.movie_filter, name='movie_filter'),
    path('movies/movie_search/', views.movie_search, name='movie_search'),
    path('movies/movie_mbti/', views.movie_mbti, name='movie_mbti'),
    path('movies/movie_mbti_search/', views.movie_mbti_search, name='movie_mbti_search'),
    path('movies/<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('movies/<int:movie_pk>/like/', views.like, name='like'),
    path('movies/<int:movie_pk>/review_create/', views.review_create, name='review_create'),
    path('movies/<int:movie_pk>/reviews_delete/<int:review_pk>/', views.reviews_delete, name='reviews_delete'),
]

final_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" integrity="sha384-9/D4ECZvKMVEJ9Bhr3ZnUAF+Ahlagp1cyPC7h5yDlZdXs4DQ/vRftzfd+2uFUuqS" crossorigin="anonymous"></script>
  {% load static %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
  <script type="text/javascript" src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <style>
    
  body {
    background-color: white;
    opacity: 1;
  }
  </style>
</head>
<body> 

<nav class="fixed-top navbar navbar-expand-lg navbar-dark" style='background-color: black'>
  <a class="nav-link active text-white" href="{% url 'movies:first' %}"><strong>주정부리</strong></a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {% if request.user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="http://127.0.0.1:8000/admin/">관리자</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'community:index' %}">커뮤니티</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movies:movie_list' %}">보고싶어요</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movies:movie_mbti' %}">성향분석</a>
      </li>
      {% elif request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'community:index' %}"><strong>
        커뮤니티</strong></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'movies:movie_list' %}">
        <strong>보고싶어요</strong></a>
      </li>
            <li class="nav-item">
        <a class="nav-link" href="{% url 'movies:movie_mbti' %}"><strong>성향분석</strong></a>
      </li>



      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
      {% endif %}
    </ul>

    <form action="{% url 'movies:movie_search' %}" class="form-inline my-2 my-lg-0" method='GET'>
      {% csrf_token %}
      <input class='form-control mr-sm-2' type="search" placeholder='Search' aria-label='Search' name='q'>
      <button class='btn btn-secondary my-2 my-sm-0' type='submit'><i class='fas fa-search'></i></button>
    </form>

    {% if request.user.is_authenticated %}
    <form class="form-inline">
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{request.user.username}}<i class="far fa-user-circle"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'accounts:profile' request.user.username %}">프로필</a>
          <a class="dropdown-item" href="{% url 'accounts:update' %}">정보수정</a>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
        </div>
      </div>
  </form>
  {% endif %}
  </div>
</nav>

<style>
  nav {
    opacity: 0.8;
  }
</style>
<div class='container mt-5 pt-5 '> 
    {% block content  %}
    {% endblock  %}
 </div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  {% block script %}
  {% endblock %}

<script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>