accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('articles/', views.index, name='index'),
    path('<int:article_pk>/articles/', views.pur_index, name='pur_index'),
    path('articles/index_search/', views.index_search, name='index_search'),
    path('articles/create/', views.create, name='create'),
    path('articles/<int:article_pk>/', views.detail, name='detail'),
    path("articles/<int:article_pk>/update", views.update, name="update"),
    path('articles/<int:article_pk>/delete/', views.delete, name='delete'),
    path('articles/<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('', include('movies.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.first, name='first'),
    path('movies/', views.movie_list, name='movie_list'),
    # path('movies/movie_filter/<int:genre_pk>/', views.movie_filter, name='movie_filter'),
    path('movies/movie_search/', views.movie_search, name='movie_search'),
    path('movies/movie_mbti/', views.movie_mbti, name='movie_mbti'),
    path('movies/movie_mbti_search/', views.movie_mbti_search, name='movie_mbti_search'),
    path('movies/<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('movies/<int:movie_pk>/like/', views.like, name='like'),
    path('movies/<int:movie_pk>/review_create/', views.review_create, name='review_create'),
    path('movies/<int:movie_pk>/reviews_delete/<int:review_pk>/', views.reviews_delete, name='reviews_delete'),
]

movies/models.py
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=200)


class Movie(models.Model):
    adult = models.BooleanField()
    genres = models.CharField(max_length=200)
    popularity = models.IntegerField()
    original_language = models.CharField(max_length=200)
    original_title = models.CharField(max_length=200)
    poster_path = models.TextField()
    title = models.CharField(max_length=200)
    vote_average = models.IntegerField()
    vote_count = models.IntegerField()
    overview = models.TextField()
    release_date = models.DateField()
    video = models.CharField(max_length=500)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)
    # genre_relation = models.ManyToManyField(Genre, related_name = 'movies', blank=True)



class Review(models.Model): 
    star = models.IntegerField()
    content = models.TextField()
    star = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)





# class Score(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     content = models.CharField(max_length=140)
#     score = models.IntegerField()
#     movie = models.ForeignKey(Movie, related_name='scores', on_delete=models.CASCADE)

movies/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    CHOICES= [
    (1, '★☆☆☆☆'),
    (2, '★★☆☆☆'),
    (3, '★★★☆☆'),
    (4, '★★★★☆'),
    (5, '★★★★★')
    ]
    
    star = forms.IntegerField(
        label='별점',
        widget=forms.Select(
            choices = CHOICES,
            attrs={
                'style': 'width: 10rem;'
            }
        )
    )


    content = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': 1
            }
        )
    )
    class Meta:
        model = Review
        fields = ['content', 'star']

movies/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import JsonResponse
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Movie, Review, Genre
from .forms import ReviewForm
from django.db.models import Q
from .genre_info import GENRE
import datetime


def first(request):
    movies = Movie.objects.order_by('-pk')
    movies_audience = Movie.objects.order_by('-popularity')
    movies_rank = Movie.objects.order_by('-vote_average')
    movies_release_date = Movie.objects.order_by('-release_date')
    context = {
        'movies': movies,
        'movies_audience': movies_audience,
        'movies_rank': movies_rank,
        'movies_release_date': movies_release_date,
    }
    return render(request, 'movies/first.html', context)



def movie_list (request):
    movies = Movie.objects.order_by('-pk')
    genre_date = request.GET.getlist('genre_list')
    pick_date = request.GET.getlist('date_list')

    if genre_date:
        for ge in GENRE:
            if ge['name'] == genre_date[0]:
                genre_i = ge['id']
        movies = movies.filter(genres__icontains=genre_i)


    if pick_date:
        p_date = pick_date[0]
        if p_date == '80-90년대':
            movies = movies.filter(release_date__lte=datetime.date(1999, 12, 31))
        elif p_date == '2000년대':
            movies = movies.filter(release_date__gte=datetime.date(2000, 1, 1)).filter(release_date__lte=datetime.date(2009, 12, 31))
        elif p_date == '2010년대 이후':
            movies = movies.filter(release_date__gte=datetime.date(2009, 12, 31))
    
    genres = []
    for gn in GENRE:
        genres.append(gn['name'])



    dates = ['80-90년대','2000년대', '2010년대 이후']
    context = {
        'movies': movies,
        'genres': genres,
        'dates': dates,
    }
    return render(request, 'movies/index.html', context)


def movie_mbti(request):

    return render(request, 'movies/movie_mbti.html')


@require_GET
def movie_mbti_search(request):
    movies = Movie.objects.order_by('-pk')
    make_mbti = []
    first = request.GET.get('first_value')
    second = request.GET.get('second_value')
    third = request.GET.get('third_value')
    fourth = request.GET.get('fourth_value')
    make_mbti.append(first)
    make_mbti.append(second)
    make_mbti.append(third)
    make_mbti.append(fourth)
    
#  User.objects.filter(Q(first_name__startswith='R')|Q(last_name__startswith='D'))

    if make_mbti == ['짬뽕','찍먹','비냉','밀떡'] :
        movies = movies.filter(Q(genres__icontains=12) | Q (genres__icontains=14))
        ment = '당신은 주정부리식 ISTJ 소금형 사람입니다.'

    elif make_mbti == ['짬뽕','찍먹','물냉','밀떡']:
        movies = movies.exclude(genres__icontains =14)
        ment = '당신은 주정부리식 ESTJ 사업가형 사람입니다.'

    elif make_mbti == ['짜장','부먹','물냉','쌀떡']:
        movies = movies.filter(Q(genres__icontains=37) | Q (genres__icontains=36))
        ment = '당신은 주정부리식 ISFJ 권력형 사람입니다.'

    elif make_mbti == ['짬뽕','부먹','물냉','밀떡']:
        movies = movies.filter(Q(genres__icontains=27) | Q (genres__icontains=53))
        ment = '당신은 주정부리식 ENFP 스파크형 사람입니다.'
    
    elif make_mbti == ['짜장','부먹','물냉','밀떡']:
        movies =  movies.filter(Q(genres__icontains=10751) | Q (genres__icontains=18) | Q(popularity__gte=52))
        ment = '당신은 주정부리식 ESFJ 친선도모형 사람입니다.'

    elif make_mbti == ['짜장','찍먹','물냉','쌀떡']:
        movies = movies.filter(Q(genres__icontains=10402) | Q (genres__icontains=99))
        ment = '당신은 주정부리식 INFP 잔다르크형 사람입니다.'

    elif make_mbti == ['짬뽕','부먹','비냉','쌀떡']:
        movies = movies.filter(Q(genres__icontains=10751) | Q (genres__icontains=10749))
        ment = '당신은 주정부리식 ISFP 성인군자형 사람입니다.'

    elif make_mbti == ['짜장','부먹','비냉','쌀떡']:
        movies = movies.filter(Q(genres__icontains=878))
        ment = '당신은 주정부리식 INTJ 과학자형 사람입니다.'

    elif make_mbti == ['짬뽕','찍먹','물냉','쌀떡']:
        movies = movies.filter(Q(popularity__gte=52)| Q(vote_average__gte=7.0))
        ment = '당신은 주정부리식 ESFP 사교형 사람입니다.'

    elif make_mbti == ['짜장','부먹','비냉','밀떡']:
        movies = movies.filter(Q(genres__icontains=9648)| Q(vote_average__gte=7.0))
        ment = '당신은 주정부리식 ISTP 백과사전형 사람입니다.'

    elif make_mbti == ['짬뽕','부먹','비냉','밀떡']:
        movies = movies.filter(Q(popularity__gte=52)| Q(release_date__lte=datetime.date(1999, 12, 31)))
        ment = '당신은 주정부리식 ISTP 백과사전형 사람입니다.'

    elif make_mbti == ['짜장','찍먹','물냉','밀떡']:
        movies = movies.all()
        ment = '당신은 주정부리식 ESTP 활동가형 사람입니다.'

    elif make_mbti == ['짜장','찍먹','비냉','밀떡']:
        movies = movies.filter(Q(genres__icontains=28)| Q(genres__icontains=10752))
        ment = '당신은 주정부리식 INTP 아이디어형 사람입니다.'

    elif make_mbti == ['짬뽕','부먹','물냉','쌀떡']:
        movies = movies.filter(Q(genres__icontains=28)| Q(genres__icontains=14))
        ment = '당신은 주정부리식 ENTJ 지도자형 사람입니다.'

    elif make_mbti == ['짬뽕','찍먹','비냉','쌀떡']:
        movies = movies.filter(Q(genres__icontains=14)| Q(genres__icontains=878))
        ment = '당신은 주정부리식 ENTP 발명가형 사람입니다.'

    elif make_mbti == ['짜장','찍먹','비냉','쌀떡']:
        movies = movies.filter(Q(genres__icontains=10752)| Q(genres__icontains=35))
        ment = '당신은 주정부리식 ENFJ 언변능숙형 사람입니다.'
    
    context = {
        'movies': movies,
        'ment': ment
    }
    return render(request, 'movies/index.html', context)






def movie_search(request):
    search_movies=None
    query=None

    if 'q' in request.GET:
        query =request.GET.get('q')
        movies = Movie.objects.all().filter(Q(title__contains=query) | Q(overview__contains=query))
    return render(request, 'movies/index.html', {'query':query, 'movies': movies})






def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    genre_name = []


    for gen in GENRE:
        if str(gen['id']) in movie.genres:
            genre_name.append(gen['name'])

    reviews = movie.review_set.all()
    review_form = ReviewForm()
    N=range(5)
    context= {
        'genre_name': genre_name,
        'movie': movie,
        'review_form': review_form,
        'reviews' : reviews,
        'video': 'https://www.youtube.com/embed/' + movie.video,
        'N': N,
    }
    return render(request, 'movies/detail.html', context)



@require_POST
def review_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review_form = ReviewForm(request.POST)
    if review_form.is_valid():
        review = review_form.save(commit=False)
        review.movie = movie
        review.user = request.user
        review.save()
        return redirect('movies:movie_detail', movie.pk)
    context = {
        'review_form': review_form,
        'movie': movie,
        'reviews': movie.review_set.all(),
    }
    return render(request, 'movies/detail.html', context)



@require_POST
def reviews_delete(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.user == review.user:
            review.delete()
    return redirect('movies:movie_detail', movie_pk)



@require_POST
def like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        user = request.user

        if movie.like_users.filter(pk=user.pk).exists():
        # if user in article.like_users.all():
            movie.like_users.remove(user)
            liked = False
        else:
            movie.like_users.add(user)
            liked = True

        like_status = {
            'liked': liked,
            'count': movie.like_users.count(),
        }
        print(like_status)
        return JsonResponse(like_status)
        # return redirect('articles:index')
    return redirect('accounts:login')

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


<div class='container m-0 p-0'>
  <div class='row d-flex justify-content-between'>
    <div class='pl-3 col-12 col-md-3'>
      <img id='img' src='https://image.tmdb.org/t/p/w200/{{movie.poster_path}}' class="card-img-top poster-img" style="width:130%;"alt="">
    </div>
  <div class="embed-responsive embed-responsive-16by9 d-flex justify-content-between mx-0" style="width:750px;">
    <iframe   
      class="embed-responsive-item"
      src='{{ video }}'
      frameborder="0" 
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
      allowfullscreen
    ></iframe>
  </div>
</div>

  <div class="jumbotron jumbotron-fluid p-0 m-0">
    <div class='col-md-9'>
      <br>
      <h1>{{movie.title}}</h1>
      <h5> 
        장르: {% for gen in genre_name %}
        {{gen}}
        {% endfor %}
      </h5>
      <h5>{{movie.release_date}} 개봉 </h5>
      <h5> <i class="fas fa-star" style="color: yellow;"></i>  {{movie.vote_average}}</h5>
      
      <h5>{{movie.overview|truncatechars:200}}</h5>
      <h5>언어: {{movie.original_language}}</h5>
    </div>
    <br><hr>
    {% if request.user.is_authenticated %}
    <div class='container'>
      <h3><strong>리뷰작성</strong></h3>

      <form action="{% url 'movies:review_create' movie.pk %}" method="POST" >
        {% csrf_token %}
        {% bootstrap_form review_form %}
        <input type='submit' class='btn btn-warning d-flex' style='color: white; font-weight: bold;'>
      </input>
    </form>
    {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
    {% endif %}
    <br>
    <a href="{% url 'movies:movie_list' %}"><i class="fas fa-arrow-left" style="font-size: 30px; color:black;" ></i></a>
    </div>
  </div>
  </div>
  <br>
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">리뷰</th>
        <th scope="col">평점</th>
        <th scope="col">작성자</th>
      </tr>
    </thead>
    <tbody>
    {% for review in reviews%}
      <tr>
        <th scope="row">{{forloop.revcounter}}</th>
        <td>{{review.content}}</td>
        <td>
        {% for star in N %}
          {% if forloop.counter <= review.star %}
          <i class="fas fa-star" style="color:crimson"></i>
          {% else %}
          <i class="fas fa-star" style="color:darkgray"></i>
          {% endif %}
        {% endfor %}
      </td>
      <td>{{ review.user }}&nbsp;&nbsp;&nbsp;&nbsp;
        {% if request.user == review.user %}
        <form action="{% url 'movies:reviews_delete' movie.pk review.pk%}" method="POST" class='d-inline'>
          {% csrf_token %}
          <input type="submit" value='x' class='btn btn-danger'>
        </form>
        {% endif %}

      </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>





</div>
<style>
  div > h1{
    {% comment %} color: white; {% endcomment %}
    font-weight: 600;
  }
  h5{
    {% comment %} color:whitesmoke; {% endcomment %}
    font-weight: 600;
  }
  form {
    {% comment %} color: white; {% endcomment %}
  }
</style>
{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="GET">

  <nav class="navbar navbar-expand-lg" style="z-index:2;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <span class="nav-item dropdown">
      <a class="nav-link dropdown-toggle dropdown-text" 
      style="color: black;" 
      href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <strong>
        장르별
      </strong>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      {% for genre in genres %}
          <input type="radio" id="genre" name="genre_list" value="{{genre}}"/>
          <label for="genre">{{genre}}</label>
          <br>
          {% endfor %}
        </div>
      </span>
      <span class="nav-item dropdown">
        <a class="nav-link dropdown-toggle dropdown-text" 
        style="color: black;" 
        href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <strong>
        연도별
        </strong>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% for date in dates %}
        <input type="radio" id="date" name="date_list" value="{{date}}"/>
        <label for="date">{{date}}</label>
        <br>
        {% endfor %}
      </div>
    </span>
  </div>
  <button type='submit' class='btn btn-warning' style="color: white;">선택완료</button>
</nav>
</form>





  
<section>
  {% if ment %}
  <div class= 'container text-center'>
    <br>
    <h1 class="display-6"><strong>
      {{ment}}
    </strong>
  </h1>
    <br>
  </div>
  {% endif %}
  <div class= 'row row-cols-1 row-cols-md-3'>
    {% for movie in movies %}
    <div class=" col mb-4"style="cursor:pointer;">
      <div class='card h-100 position-relative'style="border-color:white;">
        <div class='imageDiv h-100'>
          <img id='img' src='https://image.tmdb.org/t/p/w200/{{movie.poster_path}}' style=" height:500px;" class="card-img-top poster-img" alt="">  
          <div class="movie-title"><strong>{{movie.title}}</strong></div>
          <div class="overlay">
            <h5 class="card-title">
              <button OnClick="location.href ='{% url 'movies:movie_detail' movie.pk %}'" type="button" class="btn btn-secondary btn-lg" data-toggle="modal" data-target="#exampleModal" 
              data-whatever="@mdo">
              {{movie.title}}</button>
            </h5>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>  
</div>
</section>


<style>

.imageDiv {
  z-index: 1;
}

.card:hover .imageDiv {
  z-index: 0;
  filter: brightness(50%);

}

.card {
  transition: transform .3s;
}

.card:hover {
  transform: scale(1.1);
}

.card-title {
  color: white;
  font-size: 50px;
  font-family: Verdana, Geneva, Tahoma, sans-serif;
  position: absolute;
  width: 100%;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
  visibility:hidden;
}
.card:hover .card-title {
  visibility:visible;
}
.dropdown-text {
  font-size: 25px;
}
.movie-title {
  text-align: center;
  font-size:20px;
}
</style>
{% endblock %}

movies/templates/movies/movie_mbti.html
{% extends 'base.html' %}
{% load bootstrap4 %} 
{% block content %}
<div class='container text-center' >

  <form action="{% url 'movies:movie_mbti_search' %}" method='GET'>
    {% csrf_token %}
    <h1> 주정부리식 MBTI </h1>
    <hr>
    
    <input type="radio" id="first" name="first_value" value="짜장"/>
    <label for="first">짜장</label> vs 
    <input type="radio" id="first" name="first_value" value="짬뽕"/>
    <label for="first">짬뽕</label>
    <hr>
    <input type="radio" id="second" name="second_value" value="부먹"/>
    <label for="second">부먹</label> vs 
    <input type="radio" id="second" name="second_value" value="찍먹"/>
    <label for="second">찍먹</label>
      <hr>
      <input type="radio" id="third" name="third_value" value="물냉"/>
      <label for="third">물냉</label> vs 
      <input type="radio" id="third" name="third_value" value="비냉"/>
      <label for="third">비냉</label>
      <hr>
      <input type="radio" id="fourth" name="fourth_value" value="밀떡"/>
      <label for="fourth">밀떡</label> vs 
      <input type="radio" id="fourth" name="fourth_value" value="쌀떡"/>
      <label for="fourth">쌀떡</label>
      <br><br>
      <button type="submit" class='btn btn-warning'>제출</button>
    </form>

  </div>
    {% endblock %}

movies/templates/movies/review_create.html
{% extends 'base.html' %}
{% load bootstrap4 %} 
{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form class="my-5 mx-auto" action="" method="POST" style="max-width: 30rem;">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
  <hr>
  <!-- <a href="{% url 'community:index' %}">[back]</a> -->
  
  <style>
    div, a {
      {% comment %} color:white; {% endcomment %}
    }
  </style>
{% endblock %}