accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('articles/', views.index, name='index'),
    path('<int:article_pk>/articles/', views.pur_index, name='pur_index'),
    path('articles/index_search/', views.index_search, name='index_search'),
    path('articles/create/', views.create, name='create'),
    path('articles/<int:article_pk>/', views.detail, name='detail'),
    path("articles/<int:article_pk>/update", views.update, name="update"),
    path('articles/<int:article_pk>/delete/', views.delete, name='delete'),
    path('articles/<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('', include('movies.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.first, name='first'),
    path('movies/', views.movie_list, name='movie_list'),
    # path('movies/movie_filter/<int:genre_pk>/', views.movie_filter, name='movie_filter'),
    path('movies/movie_search/', views.movie_search, name='movie_search'),
    path('movies/movie_mbti/', views.movie_mbti, name='movie_mbti'),
    path('movies/movie_mbti_search/', views.movie_mbti_search, name='movie_mbti_search'),
    path('movies/<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('movies/<int:movie_pk>/like/', views.like, name='like'),
    path('movies/<int:movie_pk>/review_create/', views.review_create, name='review_create'),
    path('movies/<int:movie_pk>/reviews_delete/<int:review_pk>/', views.reviews_delete, name='reviews_delete'),
]

community/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title= models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    purpose = models.IntegerField()


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

community/forms.py
from django import forms
from .models import Article, Comment
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField


class ArticleForm(forms.Form):
    content = forms.CharField(widget=SummernoteWidget())
    content = forms.CharField(widget=SummernoteTextFormField())

class ArticleForm(forms.ModelForm):
    PUR = [
        (1, '자유게시판'),
        (2, '추천게시판'),
        (3, '건의게시판'),
    ]
    purpose = forms.IntegerField(
        label='게시판',
        widget=forms.Select(
                choices = PUR,
                attrs={
                    'style': 'width: 10rem;'
                }
            )
    )
    title = forms.CharField(
        label='제목',
    )
    content = SummernoteTextField()

    class Meta:
        model = Article
        fields = ['purpose', 'title', 'content']
        widgets = {
            'content' : SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '400px'}}),
        }

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': 1
            }
        )
    )
    class Meta:
        model = Comment
        fields = ['content']

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.http import JsonResponse
from django.core.paginator import Paginator
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required


def index_search(request):
    qs = Post.objects.all().order_by('-id')

    q = request.GET.get('q', '')
    if q: 
        qs = qs.filter(title__icontains=q)
    paginator = Paginator(qs, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'articles' : qs,
        'q' : q,
        'page_obj' : page_obj,
    }

    return render(request, 'community/index.html', context)


def pur_index(request, article_pk):
    if int(article_pk) > 3:
        return redirect('community:index')
    articles = Article.objects.filter(purpose=article_pk).order_by('-id')
    paginator = Paginator(articles, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'articles': articles,
        'page_obj': page_obj,
        'article_pk': article_pk,
    }
    return render(request, 'community/index.html', context)


@require_GET
def index(request):
    articles = Article.objects.order_by('-pk')
    paginator = Paginator(articles, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'articles': articles,
        'page_obj': page_obj,
    }

    return render(request, 'community/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST) 
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('community:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'community/create.html', context)

@require_GET
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comment_set.all()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'community/detail.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if request.user == article.user:
            article.delete()
            return redirect('community:index')
    return redirect('community:detail', article.pk)


@require_POST
def create_comment(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('community:detail', article.pk)
    context = {
        'comment_form': comment_form,
        'article': article,
        'comments': article.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)



@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('community:detail', article_pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, article_pk):
    # article = Article.objects.get(pk=pk)
    article = get_object_or_404(Article, pk=article_pk)
    # 수정하는 유저와, 게시글 작성 유저가 같은지 ?
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('community:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('community:index')
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'community/update.html', context)

community/templates/community/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form class="my-5 mx-auto" action="" method="POST" style="max-width: 30rem;">
    {% csrf_token %}
    <table>
      {% bootstrap_form form %}
    </table>
    <input type="submit" class='btn btn-warning' style="color: white;">
  </form>
  <hr>
  <a href="{% url 'community:index' %}" style="color: black;">[back]</a>

{% endblock %}

community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class='container'>
  <h2 class="text-center">DETAIL</h2>
  <div class="card my-5 mx-auto" style="width: 50rem; height: auto;">
    <div class="card-body">
      <h5 class="card-title">제목: {{ article.title }}</h5>
      <h6> 작성자 : {{article.user }}</h6>
      <hr>
      <p class="card-text">{{ article.content | safe }}</p>
      <h6 class="card-subtitle mb-2 text-muted">작성 시각: {{ article.created_at }}</h6>
      <h6 class="card-subtitle mb-2 text-muted">작성 시각: {{ article.updated_at }}</h6>
      
      
        {% if request.user == article.user %}
          {% comment %} <a href="{% url 'community:update' article.pk %}">UPDATE</a><br> {% endcomment %}
          
          <form action="{% url 'community:update' article.pk %}" method="POST" class='d-inline'>
            {% csrf_token %}
            <input class='btn btn-primary' type="submit" value="UPDATE">
          </form>
          <form action="{% url 'community:delete' article.pk %}" method="POST" class='d-inline'>
            {% csrf_token %}
            <input class='btn btn-danger' type="submit" value="DELETE">
          </form>
          {% endif %}
          <hr>
          {% if request.user.is_authenticated %}
          <form action="{% url 'community:create_comment' article.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form comment_form %}
            <input class="btn btn-warning" type="submit" style='color: white;'>
          </form>
          {% else %}
          <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
          {% endif %}

          
          <br>
          <h4><strong>댓글 목록</strong> </h4>
          <hr>
          {% for comment in comments %}
          <div>
            {{ comment.user }} - {{ comment.content }}
            {% if request.user == comment.user %}
            <form action="{% url 'community:comments_delete' article.pk comment.pk %}" method="POST" class="d-inline">
              {% csrf_token %}
              <input type="submit" value="x" class='btn btn-danger'>
            </form>
            {% endif %}
          </div>
          {% empty %}
          <p style="opacity: 0.6;"><b>댓글이 없어요..</b></p>
          {% endfor %}
          <br>
          <a href="{% url 'community:index' %}"><i class="fas fa-arrow-left" style="font-size: 30px;" ></i></a>
        </div>
      </div>
    </div>
    
<style>
  div, a {
    color:black;
  }
</style>

{% endblock  %}

community/templates/community/index.html
{% extends 'base.html' %}
{% comment %} 
{% load bootstrap4 %}
{% load bootstrap_pagination %} {% endcomment %}

{% block content %}


  <h1 class='jemok'><strong>커뮤니티</strong> </h1>
  {% if user.is_authenticated %}
  {% else %}
  <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요]</a>
  {% endif %}
  
  <div class="w-100 my-5" style="background-color: rgb(56, 56, 114); border-radius: 20px;"> 
    <div class="w-100 btn-group btn-group-sm overflow-auto" role="group">
      <button id="btn-0" class="btn btn-outline-light my-2 my-sm-0"
      onclick="location.href='{% url 'community:index' %}'">전체게시판</button>
      <button id="btn-1" class="btn btn-outline-light my-2 my-sm-0"
      onclick="location.href='{% url 'community:pur_index' 1 %}'">자유게시판</button>
      <button id="btn-2" class="btn btn-outline-light my-2 my-sm-0"
      onclick="location.href='{% url 'community:pur_index' 2 %}'">추천게시판</button>
      <button id="btn-3" class="btn btn-outline-light my-2 my-sm-0"
      onclick="location.href='{% url 'community:pur_index' 3 %}'">건의게시판</button>
    </div>
  </div>
  
  
  <table class="table">
    <thead class="col-12 thead">
      <tr class="row w-100 m-0" style="background-color: rgb(56, 56, 114); color:white">
        <th class="col-1 text-center p-1">#</th>
        <th class="col-7 col-md-8 p-1">제목</th>
        <th class="col-4 col-md-3 p-1 text-center">작성자</th>
      </tr>
    </thead>
    <tbody class="col-12">
      {% for article in page_obj %}
      <tr class="row m-0" onclick="location.href='{% url 'community:detail' article.pk %}'" style="cursor:pointer;">
        <th class="col-1 p-1 text-center">{{ article.pk }}</th>
        <td class="col-7 col-md-8 p-1 text-truncate" colspan="2">{{ article.title }} ({{ article.comment_set.all|length }})</td>
        <td class="col-4 col-md-3 p-1 text-center text-truncate">{{ article.user }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <hr>
  <a href="{% url 'community:create' %}" class=" new btn btn-outline-dark">새글작성</a>

  </div>
  

<style>
  .jemok {
    text-align: center;
  }
  .new { 
    position: absolute;
    right: 200px;
  }
</style>


{% endblock %}

community/templates/community/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <h1 class="text-center">UPDATE</h1>
  <form class="my-5 mx-auto" action="" method="POST" style="max-width: 30rem;">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'community:detail' article.pk %}">[back]</a>
{% endblock %}