accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<username>/', views.profile, name='profile'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('articles/', views.index, name='index'),
    path('<int:article_pk>/articles/', views.pur_index, name='pur_index'),
    path('articles/index_search/', views.index_search, name='index_search'),
    path('articles/create/', views.create, name='create'),
    path('articles/<int:article_pk>/', views.detail, name='detail'),
    path("articles/<int:article_pk>/update", views.update, name="update"),
    path('articles/<int:article_pk>/delete/', views.delete, name='delete'),
    path('articles/<int:article_pk>/comments/', views.create_comment, name='create_comment'),
    path('articles/<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),

]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('', include('movies.urls')),
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.first, name='first'),
    path('movies/', views.movie_list, name='movie_list'),
    # path('movies/movie_filter/<int:genre_pk>/', views.movie_filter, name='movie_filter'),
    path('movies/movie_search/', views.movie_search, name='movie_search'),
    path('movies/movie_mbti/', views.movie_mbti, name='movie_mbti'),
    path('movies/movie_mbti_search/', views.movie_mbti_search, name='movie_mbti_search'),
    path('movies/<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('movies/<int:movie_pk>/like/', views.like, name='like'),
    path('movies/<int:movie_pk>/review_create/', views.review_create, name='review_create'),
    path('movies/<int:movie_pk>/reviews_delete/<int:review_pk>/', views.reviews_delete, name='reviews_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

community/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    title= models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    purpose = models.IntegerField()


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

movies/models.py
from django.db import models
from django.conf import settings


class Genre(models.Model):
    name = models.CharField(max_length=200)


class Movie(models.Model):
    adult = models.BooleanField()
    genres = models.CharField(max_length=200)
    popularity = models.IntegerField()
    original_language = models.CharField(max_length=200)
    original_title = models.CharField(max_length=200)
    poster_path = models.TextField()
    title = models.CharField(max_length=200)
    vote_average = models.IntegerField()
    vote_count = models.IntegerField()
    overview = models.TextField()
    release_date = models.DateField()
    video = models.CharField(max_length=500)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)
    # genre_relation = models.ManyToManyField(Genre, related_name = 'movies', blank=True)



class Review(models.Model): 
    star = models.IntegerField()
    content = models.TextField()
    star = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)





# class Score(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     content = models.CharField(max_length=140)
#     score = models.IntegerField()
#     movie = models.ForeignKey(Movie, related_name='scores', on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from django.http import JsonResponse

from .forms import CustomUserCreationForm, CustomUserChangeForm

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)



@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'community:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)



def logout(request):
    auth_logout(request)
    return redirect('movies:first')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('articles:index')



@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/change_password.html', context)



@login_required
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호 변경</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %} 
{% block content %}
<form class="my-5 mx-auto" action="" method="POST" style="max-width: 30rem;">
  <h1>로그인</h1>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type='submit' class='btn btn-warning' value='로그인' style='color: white; font-weight: bold;'>
</form>

{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="jumbotron">
  <h1 class="text-center"><strong>{{ person.username }}님의 프로필</strong></h1>
  <img class="img " src="{% static '/ssunho.jpg'%}" class="rounded float-left">
  <hr>
  <h2>{{ person.username }}가 좋아요한 영화</h2>
  <h4 style="opacity: 0.9;"> {{ person.like_movies.all|length }} 편 </h4>
  <hr>
  {% for movie in person.like_movies.all %}
    <br>
    <a href="{% url "movies:movie_detail" movie.pk%}" style="color:black"><strong>{{ movie.title }}</strong></a>
    <br>
  {% empty%}
    <div><strong>좋아요한 영화가 없습니다.</strong> </div>
  {% endfor %}
 
  <hr>
  <h2>{{ person.username }}가 리뷰한 영화</h2>
  <h4 style="opacity: 0.9;">{{ person.review_set.all|length }} 편</h4>
  <hr>
  {% for review in person.review_set.all %}
    <br>
    <div><strong>{{ review.movie.title }}</strong></div>
  {% empty%}
    <div><strong>리뷰한 영화가 없습니다.</strong> </div>
  {% endfor %}

  <hr>

</div>

<hr>
<div class="jumbotron">
  <h1 class="text-center"><strong>커뮤니티 활동</strong></h1>
  <hr>
  <h2>{{ person.username }}이 작성한 게시글</h2>
  {% for article in person.article_set.all %}
    <div>{{ article.title }}</div>
  {% empty %}
    <div> 작성한 글이 없습니다. </div>
  {% endfor %}
  <hr>


  <h2>{{ person.username }}이 작성한 댓글</h2>
  {% for comment in person.comment_set.all %}
    <div>{{  comment.content }}</div>
    {% empty %}
    <div> 작성한 댓글이 없습니다. </div>
  {% endfor %}
</div>
<a href="{% url 'community:index' %}">back</a>

<hr>

<style>
  .img {
  border-radius: 50%;
  width: 150px;
}
</style>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<form class="my-5 mx-auto" action="" method="POST" style="max-width: 30rem;">
  <h1>회원가입</h1>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type='submit' class='btn btn-warning' value='회원가입' style='color: white; font-weight: bold;'>
</form>


{% endblock  %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %} 
{% block content %}
<form class="my-5 mx-auto" action="" method="POST" style="max-width: 30rem;">
  <h1>회원정보 수정</h1>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type='submit' class='btn btn-warning' value='수정' style='color: white; font-weight: bold;'>
</form>
<style>
</style>
{% endblock %}